apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:AxAO/SQn1X4rNgfhi8CN49sKdD9RphFFWYh+Wdl6WC6tKDLFIp9z16c5665lu2VvkhO4E2bzuRqWdScYAHRtIfQWHv2FBJglU0Psxw==,iv:fw6ycbZbGFWzayo9S2Maq2PTactJSbVxfovTXM5X/Iw=,tag:uZ8X9sNuBXNGj7tf5DHG7g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openai-api-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-19T12:29:13Z"
    mac: ENC[AES256_GCM,data:sLTj3hvh2/SjBIozrOojRPIhLNyEU/NVsxw2+zP2WPKkoP9ctLBbr/30Ne2m6DruITisgplDjykvdlnAvzIBo2X48hslbo+c8lo1CSxZ1bk90cuJhwYcFdIvybyVHxZavSXEu3kh3Z2pBkQ/2X4HsICEhYCx5V9yCSaE5L/nTbM=,iv:vWzAmhCzWLCvydtBGVp4k8VrOZuStqYV49/XMlWvSIQ=,tag:6ct5tfsemXUXcZj1fyNK2g==,type:str]
    pgp:
        - created_at: "2024-04-19T12:29:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQgAh9F+93wniuqONvtrY42GeuNtR7k3QzoRbvu8evh8MmX2
            w6VuS+C52uRtB4wQ6j0DJSEkDKzIqrrUPV4vUW+0vpDTpUm0exbK9LSWVMFFwjj7
            c24eCZ8/JxzQfiXG9+0DTwS3vDbksOYqNhAZvyLYjjesO+5hHB1Q1Obre02upJHc
            4ZtkHOWXkq353W5rel1zyZEWIdWsaw7yCvE7lVqtMJPsJ0BjsuZEJnSNxWGd/BJw
            MQFiABEJjaBw1frEKbbm045uZItD3xLYajKPgwZ/6kr1n/ikRL3qwyp7D7OgGKlW
            +qPbRYwL2A9dOXqnHMDAY2R1rrYtWRLtMzKRZsbTkNRoAQkCEPEKNuOTS9npmc5V
            fiHebhGupPr49USWgSWdL6wLqgNkhKmVfz6q59KKhtngn2JmUndriRmRhYHxNCpk
            llcgPAl+Ad7hXmbGWKO3uneULnzTnchwQ1/T0wLVSU57yeviyBsaNSI=
            =WpvE
            -----END PGP MESSAGE-----
          fp: 3D16CEE4A27381B4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
