apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:gOfb3lX5xYHQL/W7hAM2TlPAOQXE9BVPgIvcbmPDm8tFs3MxZT9VlAF1ze+qnQrXeDdbitaCeNHNrK8hV4jOttXcd4Krnq3B96ED1lJAx89jZVy4uzlv4gBNj/zqYProZ3+Kf8yFvMpmoh+XFtfNJjhsntjcllQx9Z6Q4Gms8/a1a5KoUZ4f37P5zRF/Ntxk38wQEVZHjDIUqMhTaLh8uaGnjjPEoAaRTOota+d2pmILYG0gfHZ4YTWYHA+6FjAv6rmm/4dDyTeuvoDppoJQHQ8CpdCHByIcdYkpxQ==,iv:1Iirhnrdzt+OsUO2NL6QZMmBsh5cAvdQSFZ/WRJy2rk=,tag:E0W9uYogVwy2V/GXFcBEcA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: openai-api-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-07T21:12:08Z"
    mac: ENC[AES256_GCM,data:ldwfXH6rLsqwzaYrfG044/HtDbvEe8uqnbAYSP7JcBwvFHdZYbbbDkqWC+5fb1GSxoy6SdirmyPRhbD/gXXmSAwbSa7ljRLhP1i/JFiNlW7c0Z7tyz5vdczpuz99mz7Ha4WU+GsEI0NrtTJNZ6xZhcfZ1zzLh1jBJt5oOoQH2Xg=,iv:1SMczlkjrXBN1VFbglR1Qg+GEk3xep/fbvCANhV72Ws=,tag:aWvVk9WYRIVJB5A5jLrDiA==,type:str]
    pgp:
        - created_at: "2025-04-07T21:12:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQf+PZ30SBQTwSfV4LxZR2Ld8qaJUoDkjeH0QReuLkt6EZ3P
            lYlwhEQHBMugmMQkJo82dEv2qpqpIeCW8VhmDTOtN2nLLzmKpRejICviwIDPsh/l
            +OEqfoUQl1EGWciaipR61NIVRRf6mjRM0DtGRZ7A3rpLwrY8bPJorsqPjv58rjkb
            mY7bEF76rwkGWSPqTykbFBAJp2JvcZ391q3R8DV3cO+bqVmVR3RTTndVeQQcET6x
            Q6shtlar1PRH1qPqWPGeN0gVTjSflrfBApO37h6oJAW4neQqRRIfveDh6rInHhyf
            2Ex5NGPc9cVnU7DSpAC3PLfFDcrumKUTF/HxlviIcdRoAQkCEE3lG8fz9gf1pkLJ
            FWn0jdb3wL7BZugIkeRZjimtWzezwx1b55wxzWFo/wtYsnrZn8v+YfEl2vXI6++8
            IblbhmtcJw9TQ7Rgskz+7ZpBlgT1AGp0fUaZLYm6HJZgDJPdvt/jlm0=
            =vfrY
            -----END PGP MESSAGE-----
          fp: 3D16CEE4A27381B4
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
