apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratings-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 