version: "3.8"

services:
  joke-server:
    image: joke-server:latest
    build:
      context: ../../
      dockerfile: ./cmd/joke-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NATS_URL=nats://nats:4222
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
    depends_on:
      - nats
    networks:
      - joke-network

  joke-worker:
    image: joke-worker:latest
    build:
      context: ../../
      dockerfile: ./cmd/joke-worker/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NATS_URL=nats://nats:4222
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - nats
      - mongo
      - redis
    networks:
      - joke-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    environment:
      - NATS_ENABLE_AUTH=yes
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
    networks:
      - joke-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - joke-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - joke-network

networks:
  joke-network:
    driver: bridge