apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal.company.com.server: |
    internal.company.com:53 {
      errors
      cache 10
      forward . PLACEHOLDER_VPC_DNS_IP
      reload
    } 