apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: dev
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  statefulSet:
    spec:
      template:
        spec:
          serviceAccountName: mongodb-kubernetes-operator
          containers:
          - name: mongod
            readinessProbe:
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 10
          - name: mongodb-agent
            readinessProbe:
              initialDelaySeconds: 30
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 5
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: demo
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: user
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: user-password
  namespace: dev
type: Opaque
stringData:
  password: spectrocloud