apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: dev
  labels:
    region: milan
spec:
  members: 3  # Primary region gets 3 members for majority
  type: ReplicaSet
  version: "6.0.5"
  statefulSet:
    spec:
      template:
        spec:
          serviceAccountName: mongodb-kubernetes-operator
          containers:
          - name: mongod
            readinessProbe:
              exec:
                command:
                  - /usr/bin/mongosh
                  - --eval
                  - db.adminCommand('ping')
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 10
          - name: mongodb-agent
            readinessProbe:
              exec:
                command:
                  - /opt/scripts/readinessprobe
              initialDelaySeconds: 30
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 5
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: demo
      db: admin
      passwordSecretRef:
        name: user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: user
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

---
apiVersion: v1
kind: Secret
metadata:
  name: user-password
  namespace: dev
type: Opaque
stringData:
  password: spectrocloud

