apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratings-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi 